### ISSUE TITLE
Import Error in python2.7:  Attempted relative import in non-package

### ISSUE THREAD

**Issue by beyondwait** [oanda/py-position-aggregation#1]
import oandapy
  File "C:\Python27\Lib\site-packages\oandapy\oandapy.py", line 3, in <module>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    from .exceptions import BadEnvironment, OandaError
ValueError: Attempted relative import in non-package

**Comment by beyondwait** [comment]
post put in wrong place
